-- >> DATABASE EXPLORATION

-- Exploring tables in database
SELECT *
FROM INFORMATION_SCHEMA.TABLES

--Exploring columns in database
SELECT * 
FROM INFORMATION_SCHEMA.COLUMNS

-- >> DIMENSIONS EXPLORATION

-- Explore all countries our customers come from
SELECT DISTINCT country
FROM gold.dim_customers

--Explore all categories "The major divisions"
SELECT DISTINCT category, subcategory, product_name FROM gold.dim_products
ORDER BY 1,2,3

-- >> DATE EXPLORATION

-- Find the date of the first and last order
-- How many years of sales are available?
SELECT 
	MIN(order_date) first_order_date, 
	MAX(order_date) last_order_date,
	DATEDIFF(year, MIN(order_date), MAX(order_date)) order_range_years
FROM gold.fact_sales

-- Find the youngest and oldest customer
SELECT
	MIN(birthdate) youngest_birthdate,
	DATEDIFF(year, MIN(birthdate), GETDATE()) oldest_age,
	MAX(birthdate) oldest_birthdate,
	DATEDIFF(year, MAX(birthdate), GETDATE()) youngest_age
FROM gold.dim_customers

-- >> MEASURES EXPLORATION

-- Find the total sales
SELECT SUM(sales_amount) total_sales FROM gold.fact_sales

-- Find how many items are sold
SELECT SUM(quantity) items_sold FROM gold.fact_sales

-- Find the average selling price
SELECT AVG(price) average_price FROM gold.fact_sales

-- Find the total number of orders
SELECT COUNT(DISTINCT order_number) total_orders FROM gold.fact_sales

-- Find the total number of products
SELECT COUNT(DISTINCT product_key) total_products FROM gold.dim_products

-- Find the total number of customers
SELECT COUNT(DISTINCT customer_key) total_customers FROM gold.dim_customers

-- Find the total number of customers that has placed an order
SELECT COUNT(DISTINCT customer_key) total_customers FROM gold.fact_sales

-- Generate a report that shows all key metrics of the business

SELECT 'Total Sales' AS measure_name, SUM(sales_amount) AS measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Total Quantity', SUM(quantity) FROM gold.fact_sales
UNION ALL
SELECT 'Average Price', AVG(price) FROM gold.fact_sales
UNION ALL
SELECT 'Total Orders', COUNT(DISTINCT order_number) FROM gold.fact_sales
UNION ALL
SELECT 'Total Products', COUNT(DISTINCT product_key) FROM gold.dim_products
UNION ALL
SELECT 'Total Customers', COUNT(DISTINCT customer_key) FROM gold.dim_customers

-- >> Magnitude Analysis

-- Find total customers by country
SELECT 
	country,
	COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC

-- Find total customers by gender
SELECT 
	gender,
	COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC

-- Find total products by category
SELECT 
category,
COUNT(product_key) AS total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC

-- What is the average cost in each category?
SELECT 
category,
AVG(cost) AS average_cost
FROM gold.dim_products
GROUP BY category
ORDER BY average_cost DESC

-- What is the total revenue generated for each category?
SELECT
p.category,
SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON f.product_key = p.product_key
GROUP BY p.category
ORDER BY total_revenue DESC

-- Find total revenue generated by each customer
SELECT
c.customer_key,
c.first_name,
c.last_name,
SUM(f.sales_amount) total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON f.customer_key = c.customer_key
GROUP BY 
c.customer_key,
c.first_name,
c.last_name
ORDER BY total_revenue DESC

-- What is the distribution of sold items across countries?
SELECT
c.country,
SUM(f.quantity) total_sold_items
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON f.customer_key = c.customer_key
GROUP BY c.country
ORDER BY total_sold_items DESC

-- >> Ranking Analysis

-- Which 5 products generate the highest revenue?
SELECT TOP 5
p.product_name,
SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON f.product_key = p.product_key
GROUP BY p.product_name
ORDER BY total_revenue DESC

-- What are the 5 worst performing products in terms of sales?
SELECT TOP 5
p.product_name,
SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON f.product_key = p.product_key
GROUP BY p.product_name
ORDER BY total_revenue 
